#!/usr/bin/env bash
#configures an Nginx server to listen on port 80.

# create a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory
In -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
# terminates the first nginx process ID
kill "$(pgrep 'nginx' l head -1)"
